export const posts = [
  {
    author: "Regina Filange",
    title: "Web development: Do we really need it or are birds fake",
    publishDate: "22 Sep",
    readTimeMinutes: "4",
    numberOfReactions: "11",
    numberOfComments: "8",
    tags: ["html", "css", "js"],
  },
  {
    author: "Ace Ventura",
    title: "Javascript, or: Why I have insomnia",
    publishDate: "21 Sep",
    readTimeMinutes: "12",
    numberOfReactions: "20",
    numberOfComments: "9",
    tags: ["js", "node", "react", "mongo"],
  },
  {
    author: "Doom Guy",
    title: "Dummies guide to the MERN stack",
    publishDate: "20 Sep",
    readTimeMinutes: "30",
    numberOfReactions: "18",
    numberOfComments: "11",
    tags: ["html", "css", "js", "mongo", "express", "react", "node"],
  },
  {
    author: "Silliam Wmith",
    title: "Intro to React Router, with Routing",
    publishDate: "19 Sep",
    readTimeMinutes: "12",
    numberOfReactions: "5",
    numberOfComments: "8",
    tags: ["react", "react-router", "node"],
  },
  {
    author: "Regina Filange",
    title: "Web development: Do we really need it or are birds fake",
    publishDate: "22 Sep",
    readTimeMinutes: "4",
    numberOfReactions: "11",
    numberOfComments: "8",
    tags: ["html", "css", "js"],
  },
];
